- name: Install apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    state: present

- name: Install vim
  become: true
  apt:
    name: vim
    state: present

- name: New kernel module
  become: true
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Set kernel parameters
  become: true
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Update enabled cgroups
  become: true
  replace:
    path: /boot/cmdline.txt
    regexp: '(rootwait)$'
    replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1'

- name: Disable swap at boot
  cron:
    name: 'disable swap'
    special_time: reboot
    job: sudo /sbin/swapoff -a

- name: Reboot
  become: true
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: not ansible_check_mode

- name: Wait for reboot
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300
  when: not ansible_check_mode

- name: Enable k8s Apt repo
  become: true
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main

- name: Create Apt keyrings dir
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Add Docker GPG key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Add Docker sources
  become: true
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable

- name: Add Kubernetes GPG key
  become: true
  shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Install containerd
  become: true
  apt:
    name: containerd.io
    update_cache: true

- name: Install k8s packages
  become: true
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl

- name: Hold kubelet
  become: true
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubeadm
  become: true
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubectl
  become: true
  dpkg_selections:
    name: kubectl
    selection: hold

- name: Create CNI dir
  become: true
  file:
    path: /opt/cni/bin
    state: directory

- name: Copy containerd config
  become: true
  copy:
    src: files/containerd_config.toml
    dest: /etc/containerd/config.toml

- name: Restart containerd
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: containerd

- name: Pull kubeadm images
  become: true
  shell: kubeadm config images pull
