# Prevents SSH brute force attacks
- name: Install fail2ban
  become: true
  apt:
    name: fail2ban
    state: present

# Installs firewall
- name: Install ufw
  become: true
  apt:
    name: ufw
    state: present

# Rate limits SSH attempts
- name: Limit ssh
  become: true
  ufw:
    rule: limit
    port: ssh
    proto: tcp

# Firewall rules
- name: Allow some access from the main VLAN
  become: true
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
    src: '10.1.0.0/24'
  loop:
    - 22
    - 53
    - 443
    - 6443

- name: Allow all from inside the VLAN
  become: true
  ufw:
    rule: allow
    src: '10.4.0.0/24'

- name: Enable logging
  become: true
  ufw:
    logging: on

- name: Enable ufw and default to deny
  become: true
  ufw:
    state: enabled
    default: deny
