# Update system-level dependencies
- name: Wait for sudo
  become: yes
  shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: dist
    update_cache: true

# Automatically upgrade apt packages
- name: Install unattended upgrades
  become: true
  apt:
    name: unattended-upgrades
    state: present

- name: Setup unattended upgrades
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: "true"
