controller:
  reportNodeInternalIp: true
  watchIngressWithoutClass: true
  service:
    enableHttp: false
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/loadBalancerIPs: "10.4.0.224"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
