apiVersion: v1
kind: Service
metadata:
  name: blocky
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.4.0.225"
  labels:
    app.kubernetes.io/name: blocky
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: blocky
  ports:
    - name: dns
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: web
      port: 4000
      targetPort: web
