repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: cilium
    url: https://helm.cilium.io/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: longhorn
    url: https://charts.longhorn.io
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: metallb
    url: https://metallb.github.io/metallb

templates:
  defaults: &defaults
    namespace: ops
    missingFileHandler: Info
    values:
      - ./values/{{`{{.Release.Name}}`}}.yaml
    secrets:
      - ./secrets/{{`{{.Release.Name}}`}}.yaml

releases:
  - name: cilium
    <<: *defaults
    chart: cilium/cilium
    version: 1.12.4

  - name: metallb
    <<: *defaults
    chart: metallb/metallb
    version: 0.13.7
    needs:
      - prometheus

  - name: network-config
    <<: *defaults
    chart: ./charts/network-config
    version: 0.0.1
    needs:
      - cilium
      - metallb

  - name: longhorn
    <<: *defaults
    chart: longhorn/longhorn
    version: 1.3.2
    namespace: longhorn-system

  - name: cert-manager
    <<: *defaults
    chart: jetstack/cert-manager
    version: 1.10.1

  - name: letsencrypt-cert
    <<: *defaults
    chart: ./charts/letsencrypt-cert
    version: 0.0.1
    needs:
      - cert-manager

  - name: ingress-nginx
    <<: *defaults
    chart: ingress-nginx/ingress-nginx
    version: 4.4.0

  - name: prometheus
    <<: *defaults
    chart: prometheus-community/kube-prometheus-stack
    version: 42.1.0
    needs:
      - longhorn-system/longhorn

  - name: longhorn-metrics
    <<: *defaults
    chart: ./charts/longhorn-metrics
    version: 0.0.1
    namespace: longhorn-system
    needs:
      - longhorn

  - name: blocky
    <<: *defaults
    chart: ./charts/blocky
    version: 0.0.1
    namespace: blocky
    needs:
      - longhorn-system/longhorn

  - name: powerdns-auth
    <<: *defaults
    chart: ./charts/powerdns-auth
    version: 0.0.1
    namespace: powerdns
    needs:
      - longhorn-system/longhorn

  - name: powerdns-recursor
    <<: *defaults
    chart: ./charts/powerdns-recursor
    version: 0.0.1
    namespace: powerdns
    needs:
      - longhorn-system/longhorn

  - name: external-dns
    <<: *defaults
    chart: bitnami/external-dns
    version: 6.12.1
    namespace: powerdns
    needs:
      - powerdns-auth
