repositories:
  - name: projectcalico
    url: https://projectcalico.docs.tigera.io/charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: longhorn
    url: https://charts.longhorn.io
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: truecharts
    url: https://library-charts.truecharts.org
  - name: coredns
    url: https://coredns.github.io/helm

templates:
  defaults: &defaults
    namespace: ops
    missingFileHandler: Info
    values:
      - ./values/{{`{{.Release.Name}}`}}.yaml
    secrets:
      - ./secrets/{{`{{.Release.Name}}`}}.yaml

releases:
  - name: calico
    <<: *defaults
    chart: projectcalico/tigera-operator
    version: 3.24.5

  - name: longhorn
    <<: *defaults
    chart: longhorn/longhorn
    version: 1.3.2
    namespace: longhorn-system
    needs:
      - ops/calico

  - name: cert-manager
    <<: *defaults
    chart: jetstack/cert-manager
    version: 1.10.1
    needs:
      - calico

  - name: letsencrypt-cert
    <<: *defaults
    chart: ./charts/letsencrypt-cert
    version: 0.0.1
    needs:
      - calico
      - cert-manager

  - name: ingress-nginx
    <<: *defaults
    chart: ingress-nginx/ingress-nginx
    version: 4.4.0
    needs:
      - calico

  - name: prometheus
    <<: *defaults
    chart: prometheus-community/kube-prometheus-stack
    version: 42.1.0
    needs:
      - calico
      - longhorn-system/longhorn

  - name: adguard-home
    <<: *defaults
    chart: truecharts/adguard-home
    version: 3.0.2
    needs:
      - calico
      - longhorn-system/longhorn

  # A distinct deployment from the one used for internal k8s DNS
  - name: coredns
    <<: *defaults
    chart: coredns/coredns
    version: 1.19.7
    needs:
      - calico
      - longhorn-system/longhorn
