repositories:
  - name: projectcalico
    url: https://projectcalico.docs.tigera.io/charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: longhorn
    url: https://charts.longhorn.io
  - name: jetstack
    url: https://charts.jetstack.io

templates:
  defaults: &defaults
    namespace: ops
    values:
      - ./values/{{`{{.Release.Name}}`}}.yaml

releases:
  - name: calico
    <<: *defaults
    chart: projectcalico/tigera-operator
    version: 3.24.5

  - name: longhorn
    <<: *defaults
    chart: longhorn/longhorn
    version: 1.3.2
    namespace: longhorn-system
    needs:
      - ops/calico

  - name: prometheus
    <<: *defaults
    chart: prometheus-community/kube-prometheus-stack
    version: 42.0.3
    needs:
      - calico
      - longhorn-system/longhorn
